#!/usr/bin/env bash

SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

# Set background
if [ -x "$(command -v feh)" ]; then
  feh --bg-fill $SCRIPTPATH/down.jpg
fi

echo "UnloadTheme" > $XDG_RUNTIME_DIR/leftwm/commands.pipe

pkill polybar &
pkill xcompmgr &
pkill dunst &
pkill redshift-gtk &
pkill nm-applet &
pkill volumeicon &
pkill octoxbps-notifier &
pkill udiskie &
pkill xautolock &
pkill cabtticon &
