#!/bin/bash

set -eu

. ./lib.sh

PROGNAME=$(basename "$0")
ARCH=$(uname -m)
IMAGES="niri plasma"
TRIPLET=
REPO=
DATE=$(date -u +%Y%m%d)

usage() {
	cat <<-EOH
	Usage: $PROGNAME [options ...] [-- mklive options ...]

	Wrapper script around mklive.sh for several standard flavors of live images.
	Adds d77void-installer and other helpful utilities to the generated images.
        
	adaptation of mkiso.sh by Daniel Azevedo (dani-77) 

	OPTIONS
	 -a <arch>     Set architecture (or platform) in the image. Asahi is untested for Duff-Linux.
	 -b <variant>  Use "noctalia" for the niri variant.
               May be specified multiple times to build multiple variants.
	 -d <date>     Override the datestamp on the generated image (YYYYMMDD format)
	 -t <arch-date-variant>
	               Equivalent to setting -a, -b, and -d
	 -r <repo>     Use this XBPS repository. May be specified multiple times
	 -h            Show this help and exit
	 -V            Show version and exit

	Other options can be passed directly to mklive.sh by specifying them after the --.
	See mklive.sh -h for more details.
	EOH
}

while getopts "a:b:d:t:hr:V" opt; do
case $opt in
    a) ARCH="$OPTARG";;
    b) IMAGES="$OPTARG";;
    d) DATE="$OPTARG";;
    r) REPO="-r $OPTARG $REPO";;
    t) TRIPLET="$OPTARG";;
    V) version; exit 0;;
    h) usage; exit 0;;
    *) usage >&2; exit 1;;
esac
done
shift $((OPTIND - 1))

INCLUDEDIR=$(mktemp -d)
trap "cleanup" INT TERM

cleanup() {
    rm -rf "$INCLUDEDIR"
}

include_installer() {
    if [ -x installer.sh ]; then
        MKLIVE_VERSION="$(PROGNAME='' version)"
        installer=$(mktemp)
        sed "s/@@MKLIVE_VERSION@@/${MKLIVE_VERSION}/" installer.sh > "$installer"
        install -Dm755 "$installer" "$INCLUDEDIR"/usr/bin/d77void-installer
        rm "$installer"
    else
        echo installer.sh not found >&2
        exit 1
    fi
}

setup_pipewire() {
    PKGS="$PKGS pipewire alsa-pipewire"
    case "$ARCH" in
        asahi*)
            PKGS="$PKGS asahi-audio"
            SERVICES="$SERVICES speakersafetyd"
            ;;
    esac
    mkdir -p "$INCLUDEDIR"/etc/xdg/autostart
    ln -sf /usr/share/applications/pipewire.desktop "$INCLUDEDIR"/etc/xdg/autostart/
    mkdir -p "$INCLUDEDIR"/etc/pipewire/pipewire.conf.d
    ln -sf /usr/share/examples/wireplumber/10-wireplumber.conf "$INCLUDEDIR"/etc/pipewire/pipewire.conf.d/
    ln -sf /usr/share/examples/pipewire/20-pipewire-pulse.conf "$INCLUDEDIR"/etc/pipewire/pipewire.conf.d/
    mkdir -p "$INCLUDEDIR"/etc/alsa/conf.d
    ln -sf /usr/share/alsa/alsa.conf.d/50-pipewire.conf "$INCLUDEDIR"/etc/alsa/conf.d
    ln -sf /usr/share/alsa/alsa.conf.d/99-pipewire-default.conf "$INCLUDEDIR"/etc/alsa/conf.d
}

include_common() {
	mkdir -p "$INCLUDEDIR"/boot/grub/themes
	mkdir -p "$INCLUDEDIR"/etc
	mkdir -p "$INCLUDEDIR"/etc/skel/.config
	mkdir -p "$INCLUDEDIR"/etc/skel/.local/share
	mkdir -p "$INCLUDEDIR"/etc/default
	mkdir -p "$INCLUDEDIR"/etc/skel/.local/share
	mkdir -p "$INCLUDEDIR"/usr/bin
	mkdir -p "$INCLUDEDIR"/usr/lib
	mkdir -p "$INCLUDEDIR"/usr/share/applications
	mkdir -p "$INCLUDEDIR"/usr/share/pixmaps
	mkdir -p "$INCLUDEDIR"/usr/share/plymouth/themes
	mkdir -p "$INCLUDEDIR"/usr/share/polkit-1/rules.d
	mkdir -p "$INCLUDEDIR"/usr/share/void-artwork
	mkdir -p "$INCLUDEDIR"/usr/share/sddm/faces
	mkdir -p "$INCLUDEDIR"/usr/share/sddm/themes
	cp -r ./common/d77-grub-theme "$INCLUDEDIR"/boot/grub/themes/
	cp -r ./common/calamares "$INCLUDEDIR"/etc/
	cp -r ./common/d77 "$INCLUDEDIR"/usr/share/plymouth/themes/
	cp -r ./common/d77-spinner "$INCLUDEDIR"/usr/share/plymouth/themes/
	cp -r ./common/.bash_it "$INCLUDEDIR"/etc/skel/
	cp -r $variant/skel "$INCLUDEDIR"/etc/
	cp ./common/asound.conf "$INCLUDEDIR"/etc/
	cp ./common/sddm.conf "$INCLUDEDIR"/etc/
	cp ./common/grub "$INCLUDEDIR"/etc/default/
	cp ./common/.gtkrc-2.0 "$INCLUDEDIR"/etc/skel/
	cp ./common/.bashrc "$INCLUDEDIR"/etc/skel/
	cp ./common/.Xresources "$INCLUDEDIR"/etc/skel/
	cp ./common/d77-welcome "$INCLUDEDIR"/usr/bin/
	cp ./common/50-udisks.rules "$INCLUDEDIR"/usr/share/polkit-1/rules.d/
	cp ./common/d77-welcome.desktop "$INCLUDEDIR"/usr/share/applications/
	cp ./common/d77void.png "$INCLUDEDIR"/usr/share/pixmaps/
	cp ./common/splash.png "$INCLUDEDIR"/usr/share/void-artwork/
	cp ./common/anon.face.icon "$INCLUDEDIR"/usr/share/sddm/faces/
	cp -r ./common/gtksourceview-4 "$INCLUDEDIR"/etc/skel/.local/share/
	cp -r ./common/config/* "$INCLUDEDIR"/etc/skel/.config/
	cp -r ./common/themes "$INCLUDEDIR"/etc/skel/.local/share/
	cp -r ./common/.icons "$INCLUDEDIR"/etc/skel/
	cp -r ./common/Wallpaper "$INCLUDEDIR"/etc/skel/
	cp -r ./common/lib-d77-welcome "$INCLUDEDIR"/usr/lib/
	cp -r ./common/slice "$INCLUDEDIR"/usr/share/sddm/themes/
	cp -r ./common/Wallpaper "$INCLUDEDIR"/usr/share/
}

include_niri() {
	mkdir -p "$INCLUDEDIR"/usr/bin
	cp ./common/dconf_niri "$INCLUDEDIR"/usr/bin/
	cp ./common/sww "$INCLUDEDIR"/usr/bin/
	cp ./common/niri_1st "$INCLUDEDIR"/usr/bin/
	cp ./common/screenlock "$INCLUDEDIR"/usr/bin/
} 

include_plasma() {
	mkdir -p "$INCLUDEDIR"/boot/grub/themes
	mkdir -p "$INCLUDEDIR"/etc
	mkdir -p "$INCLUDEDIR"/etc/skel/.config
	mkdir -p "$INCLUDEDIR"/etc/skel/.local/share
	mkdir -p "$INCLUDEDIR"/etc/default
	mkdir -p "$INCLUDEDIR"/etc/skel/.local/share
	mkdir -p "$INCLUDEDIR"/usr/bin
	mkdir -p "$INCLUDEDIR"/usr/lib
	mkdir -p "$INCLUDEDIR"/usr/share/applications
	mkdir -p "$INCLUDEDIR"/usr/share/backgrounds
	mkdir -p "$INCLUDEDIR"/usr/share/pixmaps
	mkdir -p "$INCLUDEDIR"/usr/share/plymouth/themes
	mkdir -p "$INCLUDEDIR"/usr/share/polkit-1/rules.d
	mkdir -p "$INCLUDEDIR"/usr/share/void-artwork
	mkdir -p "$INCLUDEDIR"/usr/share/sddm/faces
	mkdir -p "$INCLUDEDIR"/usr/share/sddm/themes
	cp -r ./common/d77-grub-theme "$INCLUDEDIR"/boot/grub/themes/
	cp -r ./common/calamares "$INCLUDEDIR"/etc/
	cp -r ./common/d77 "$INCLUDEDIR"/usr/share/plymouth/themes/
	cp -r ./common/d77-spinner "$INCLUDEDIR"/usr/share/plymouth/themes/
	cp -r ./common/gnome-shell "$INCLUDEDIR"/etc/skel/.local/share/
	cp -r ./common/.bash_it "$INCLUDEDIR"/etc/skel/
	cp -r $variant/skel "$INCLUDEDIR"/etc/
	cp -r ./common/dconf "$INCLUDEDIR"/etc/
	cp ./common/asound.conf "$INCLUDEDIR"/etc/
	cp ./common/grub "$INCLUDEDIR"/etc/default/
	cp ./common/.gtkrc-2.0 "$INCLUDEDIR"/etc/skel/
	cp ./common/.bashrc "$INCLUDEDIR"/etc/skel/
	cp ./common/.Xresources "$INCLUDEDIR"/etc/skel/
	cp ./common/d77-welcome "$INCLUDEDIR"/usr/bin/
	cp ./common/50-udisks.rules "$INCLUDEDIR"/usr/share/polkit-1/rules.d/
	cp ./common/d77-welcome.desktop "$INCLUDEDIR"/usr/share/applications/
	cp ./common/d77void.png "$INCLUDEDIR"/usr/share/pixmaps/
	cp ./common/splash.png "$INCLUDEDIR"/usr/share/void-artwork/
	cp ./common/anon.face.icon "$INCLUDEDIR"/usr/share/sddm/faces/
	cp ./common/sddm.conf "$INCLUDEDIR"/etc/
	cp -r ./common/gtksourceview-4 "$INCLUDEDIR"/etc/skel/.local/share/
	cp -r ./common/config/* "$INCLUDEDIR"/etc/skel/.config/
	cp -r ./common/themes "$INCLUDEDIR"/etc/skel/.local/share/
	cp -r ./common/.icons "$INCLUDEDIR"/etc/skel/
	cp -r ./common/lib-d77-welcome "$INCLUDEDIR"/usr/lib/
	cp -r ./common/slice "$INCLUDEDIR"/usr/share/sddm/themes/
	cp -r ./common/Wallpaper "$INCLUDEDIR"/usr/share/backgrounds/
}

include_x11() {
    	PKGS="$PKGS dunst redshift scrot slock st transset xautolock xcompmgr xterm"
	cp ./common/wswap-X "$INCLUDEDIR"/usr/bin/
}		

build_variant() {
    variant="$1"
    shift
    IMG=duff-linux-live-${ARCH}-${DATE}-${variant}.iso

    # el-cheapo installer is unsupported on arm because arm doesn't install a kernel by default
    # and to work around that would add too much complexity to it
    # thus everyone should just do a chroot install anyways
    WANT_INSTALLER=no
    case "$ARCH" in
        x86_64*|i686*)
            GRUB_PKGS="grub-i386-efi grub-x86_64-efi"
            GFX_PKGS="xorg-video-drivers"
            GFX_WL_PKGS="mesa-dri"
            WANT_INSTALLER=yes
            TARGET_ARCH="$ARCH"
	    D77_CORE="acpi apulse alsa-plugins-pulseaudio alsa-tools alsa-utils arc-theme bash-completion bc brave-bin brightnessctl ca-certificates cmus cups cups-browsed curl elogind ethtool fastfetch feh font-awesome font-awesome5 font-awesome6 font-awesome7 font-hack-ttf font-iosevka geary gettext git gmrun htop inxi kvantum mousepad mpv nano NetworkManager nerd-fonts-symbols-ttf nwg-look octoxbps papirus-icon-theme pcmanfm plymouth polkit power-profiles-daemon qt5ct qt6ct qt5-graphicaleffects ranger sddm smartmontools system-config-printer tlp tlp-rdw transmission-qt udiskie ufw uget unzip usbutils util-linux vim void-repo-multilib void-repo-multilib-nonfree void-repo-nonfree wget xdg-user-dirs xdg-user-dirs-gtk xdg-utils xf86-input-synaptics xarchiver xcalc xinit xorg xorg-server xpdf yt-dlp zathura zathura-pdf-poppler"
	    CALAMARES="calamares grub rsync"
	    COMMON=
	    PLASMA=
	    X11=
	    NIRI=
	    ;;
        aarch64*)
            GRUB_PKGS="grub-arm64-efi"
            GFX_PKGS="xorg-video-drivers"
            GFX_WL_PKGS="mesa-dri"
            TARGET_ARCH="$ARCH"
            ;;
        asahi*)
            GRUB_PKGS="asahi-base asahi-scripts grub-arm64-efi"
            GFX_PKGS="mesa-asahi-dri"
            GFX_WL_PKGS="mesa-asahi-dri"
            KERNEL_PKG="linux-asahi"
            TARGET_ARCH="aarch64${ARCH#asahi}"
            if [ "$variant" = xfce ]; then
                info_msg "xfce is not supported on asahi, switching to xfce-wayland"
                variant="xfce-wayland"
            fi
            ;;
    esac

    A11Y_PKGS="espeakup void-live-audio brltty"
    PKGS="dialog cryptsetup lvm2 mdadm void-docs-browse xtools-minimal xmirror chrony tmux $A11Y_PKGS $GRUB_PKGS"
    FONTS="font-misc-misc terminus-font dejavu-fonts-ttf"
    WAYLAND_PKGS="$GFX_WL_PKGS $FONTS orca"
    XORG_PKGS="$GFX_PKGS $FONTS xorg-minimal xorg-input-drivers setxkbmap xauth orca"
    SERVICES="sshd chronyd"

    case $variant in
        base)
            SERVICES="$SERVICES dhcpcd wpa_supplicant acpid"
        ;;
	niri)
	    COMMON=yes
	    NIRI=yes
            PKGS="$PKGS $XORG_PKGS $WAYLAND_PKGS $D77_CORE $CALAMARES gnome-keyring grim ImageMagick kitty niri qt5-wayland qt6-wayland swaybg swayidle swayimg swaylock swww xdg-desktop-portal-gnome xdg-desktop-portal-gtk"
            SERVICES="$SERVICES dbus elogind sddm NetworkManager polkitd power-profiles-daemon"
        ;;
	niri-noctalia)
	    COMMON=yes
            PKGS="$PKGS $XORG_PKGS $WAYLAND_PKGS $D77_CORE $CALAMARES cliphist gnome-keyring grim ImageMagick kitty mate-polkit matugen niri noctalia-cli noctalia-qs noctalia-shell pavucontrol qt5-wayland qt6-multimedia qt6-wayland swaybg swayidle swayimg SwayNotificationCenter upower wayland-devel wayland-protocols wlsunset xdg-desktop-portal-gnome xdg-desktop-portal-gtk xorg-server-xwayland xwayland-satellite"
            SERVICES="$SERVICES dbus elogind sddm NetworkManager polkitd power-profiles-daemon"
        ;;      
	plasma)
	    PLASMA=yes
            PKGS="$PKGS $XORG_PKGS $WAYLAND_PKGS $D77_GNOME $CALAMARES ark kde5 kde5-baseapps kmail qt5-graphicaleffects sddm yakuake"
            SERVICES="$SERVICES dbus elogind sddm NetworkManager polkitd power-profiles-daemon"
        ;;
        *)
            >&2 echo "Unknown variant $variant"
            exit 1
        ;;
    esac

[greeter]
indicators = ~host;~spacer;~clock;~spacer;~layout;~session;~a11y;~power
EOF
    fi

    if [ "$COMMON" = yes ]; then
        include_common
    fi

    if [ "$NIRI" = yes ]; then
        include_niri
    fi

    if [ "$PLASMA" = yes ]; then
        include_plasma
    fi

    if [ "$X11" = yes ]; then
        include_x11
    fi

    if [ "$WANT_INSTALLER" = yes ]; then
        include_installer
    else
        mkdir -p "$INCLUDEDIR"/usr/bin
        printf "#!/bin/sh\necho 'd77void-installer is not supported on this live image'\n" > "$INCLUDEDIR"/usr/bin/d77void-installer
        chmod 755 "$INCLUDEDIR"/usr/bin/d77void-installer
    fi

    if [ "$variant" != base ]; then
        setup_pipewire
    fi

    ./mklive.sh -a "$TARGET_ARCH" -o "$IMG" -p "$PKGS" -S "$SERVICES" -I "$INCLUDEDIR" \
        ${KERNEL_PKG:+-v $KERNEL_PKG} ${REPO} "$@"

	cleanup
}

if [ ! -x mklive.sh ]; then
    echo mklive.sh not found >&2
    exit 1
fi

if [ -n "$TRIPLET" ]; then
    IFS=: read -r ARCH DATE VARIANT _ < <( echo "$TRIPLET" | sed -Ee 's/^(.+)-([0-9rc]+)-(.+)$/\1:\2:\3/' )
    build_variant "$VARIANT" "$@"
else
    for image in $IMAGES; do
        build_variant "$image" "$@"
    done
fi
