#!/bin/bash

set -eu

. ./lib.sh

PROGNAME=$(basename "$0")
ARCH=$(uname -m)
IMAGES="plasma"
TRIPLET=
REPO=
DATE=$(date -u +%Y%m%d)

usage() {
	cat <<-EOH
	Usage: $PROGNAME [options ...] [-- mklive options ...]

	Wrapper script around mklive.sh for several standard flavors of live images.
	Adds d77void-installer and other helpful utilities to the generated images.
        
	adaptation of mkiso.sh by Daniel Azevedo (dani-77) 

	OPTIONS
	 -a <arch>     Set architecture (or platform) in the image. Asahi is untested.
	 -b <variant>  Only "plasma" is supported here. (WIP)
               May be specified multiple times to build multiple variants.
	 -d <date>     Override the datestamp on the generated image (YYYYMMDD format)
	 -t <arch-date-variant>
	               Equivalent to setting -a, -b, and -d
	 -r <repo>     Use this XBPS repository. May be specified multiple times
	 -h            Show this help and exit
	 -V            Show version and exit

	Other options can be passed directly to mklive.sh by specifying them after the --.
	See mklive.sh -h for more details.
	EOH
}

while getopts "a:b:d:t:hr:V" opt; do
case $opt in
    a) ARCH="$OPTARG";;
    b) IMAGES="$OPTARG";;
    d) DATE="$OPTARG";;
    r) REPO="-r $OPTARG $REPO";;
    t) TRIPLET="$OPTARG";;
    V) version; exit 0;;
    h) usage; exit 0;;
    *) usage >&2; exit 1;;
esac
done
shift $((OPTIND - 1))

INCLUDEDIR=$(mktemp -d)
trap "cleanup" INT TERM

cleanup() {
    rm -rf "$INCLUDEDIR"
}

include_installer() {
    if [ -x installer.sh ]; then
        MKLIVE_VERSION="$(PROGNAME='' version)"
        installer=$(mktemp)
        sed "s/@@MKLIVE_VERSION@@/${MKLIVE_VERSION}/" installer.sh > "$installer"
        install -Dm755 "$installer" "$INCLUDEDIR"/usr/bin/d77void-installer
        rm "$installer"
    else
        echo installer.sh not found >&2
        exit 1
    fi
}

setup_pipewire() {
    PKGS="$PKGS pipewire alsa-pipewire"
    case "$ARCH" in
        asahi*)
            PKGS="$PKGS asahi-audio"
            SERVICES="$SERVICES speakersafetyd"
            ;;
    esac
    mkdir -p "$INCLUDEDIR"/etc/xdg/autostart
    ln -sf /usr/share/applications/pipewire.desktop "$INCLUDEDIR"/etc/xdg/autostart/
    mkdir -p "$INCLUDEDIR"/etc/pipewire/pipewire.conf.d
    ln -sf /usr/share/examples/wireplumber/10-wireplumber.conf "$INCLUDEDIR"/etc/pipewire/pipewire.conf.d/
    ln -sf /usr/share/examples/pipewire/20-pipewire-pulse.conf "$INCLUDEDIR"/etc/pipewire/pipewire.conf.d/
    mkdir -p "$INCLUDEDIR"/etc/alsa/conf.d
    ln -sf /usr/share/alsa/alsa.conf.d/50-pipewire.conf "$INCLUDEDIR"/etc/alsa/conf.d
    ln -sf /usr/share/alsa/alsa.conf.d/99-pipewire-default.conf "$INCLUDEDIR"/etc/alsa/conf.d
}

include_common() {
	mkdir -p "$INCLUDEDIR"/etc
	mkdir -p "$INCLUDEDIR"/usr/share/polkit-1/rules.d
	cp -r ./common/calamares "$INCLUDEDIR"/etc/
	cp -r $variant/skel "$INCLUDEDIR"/etc/
	cp ./common/asound.conf "$INCLUDEDIR"/etc/
	cp ./common/50-udisks.rules "$INCLUDEDIR"/usr/share/polkit-1/rules.d/
}

include_plasma() {
    # 1. Create essential directory structure
    mkdir -p "$INCLUDEDIR"/etc/skel/.config
    mkdir -p "$INCLUDEDIR"/etc/xdg/autostart
    mkdir -p "$INCLUDEDIR"/usr/share/polkit-1/rules.d

    # 1. Autostart Calamares in the Live ISO
    mkdir -p "$INCLUDEDIR"/etc/skel/.config/autostart
    ln -sf /usr/share/applications/calamares.desktop "$INCLUDEDIR"/etc/skel/.config/autostart/calamares.desktop

    # 1. Create the system-wide Flatpak remotes directory
    mkdir -p "$INCLUDEDIR"/etc/flatpak/remotes.d
    
    # 2. Download the Flathub repo file directly into the ISO
    curl -L -o "$INCLUDEDIR"/etc/flatpak/remotes.d/flathub.flatpakrepo https://dl.flathub.org/repo/flathub.flatpakrepo

    # 1. Create the SDDM configuration directory
    mkdir -p "$INCLUDEDIR"/etc/sddm.conf.d

    # 2. Generate the config file to set the theme to Breeze
    cat <<EOF > "$INCLUDEDIR"/etc/sddm.conf.d/kde_theme.conf
[Theme]
Current=breeze
EOF

    # 2. Keep functional configurations for the installer and audio
    cp -r ./common/calamares "$INCLUDEDIR"/etc/
    cp ./common/asound.conf "$INCLUDEDIR"/etc/
    cp ./common/50-udisks.rules "$INCLUDEDIR"/usr/share/polkit-1/rules.d/

    # 3. Force Breeze Dark theme for the user profile
    cat <<EOF > "$INCLUDEDIR"/etc/skel/.config/kdeglobals
[General]
ColorScheme=BreezeDark
lookAndFeelPackage=org.kde.breezedark.desktop
EOF

    # 4. Set OctoXBPS Notifier to autostart by default
    ln -sf /usr/share/applications/octoxbps-notifier.desktop "$INCLUDEDIR"/etc/xdg/autostart/
}

include_x11() {
    	PKGS="$PKGS dunst redshift scrot slock st transset xautolock xcompmgr xterm"
	cp ./common/wswap-X "$INCLUDEDIR"/usr/bin/
}		

build_variant() {
    variant="$1"
    shift
    IMG=duff-linux-live-${ARCH}-${DATE}-${variant}.iso

    # el-cheapo installer is unsupported on arm because arm doesn't install a kernel by default
    # and to work around that would add too much complexity to it
    # thus everyone should just do a chroot install anyways
    WANT_INSTALLER=no
    case "$ARCH" in
        x86_64*|i686*)
            GRUB_PKGS="grub-i386-efi grub-x86_64-efi"
            GFX_PKGS="xorg-video-drivers"
            GFX_WL_PKGS="mesa-dri"
			KERNEL_PKG="linux7.0"
            WANT_INSTALLER=yes
            TARGET_ARCH="$ARCH"
	    D77_CORE="acpi alsa-plugins-pulseaudio alsa-utils bash-completion ca-certificates curl elogind git inxi nano NetworkManager octoxbps polkit power-profiles-daemon sddm udiskie ufw unzip usbutils util-linux void-repo-multilib void-repo-multilib-nonfree void-repo-nonfree wget xdg-user-dirs xdg-user-dirs-gtk xdg-utils xinit xorg xorg-server"
	    CALAMARES="calamares grub rsync"
	    COMMON=
	    PLASMA=
	    X11=
	    ;;
        aarch64*)
            GRUB_PKGS="grub-arm64-efi"
            GFX_PKGS="xorg-video-drivers"
            GFX_WL_PKGS="mesa-dri"
			KERNEL_PKG="linux7.0"
            TARGET_ARCH="$ARCH"
            ;;
        asahi*)
            GRUB_PKGS="asahi-base asahi-scripts grub-arm64-efi"
            GFX_PKGS="mesa-asahi-dri"
            GFX_WL_PKGS="mesa-asahi-dri"
            KERNEL_PKG="linux-asahi"
            TARGET_ARCH="aarch64${ARCH#asahi}"
            ;;
    esac

    A11Y_PKGS="espeakup void-live-audio"
    PKGS="linux7.0-headers dialog cryptsetup lvm2 mdadm void-docs-browse xtools-minimal xmirror chrony tmux $A11Y_PKGS $GRUB_PKGS"
    FONTS="font-misc-misc terminus-font dejavu-fonts-ttf"
    WAYLAND_PKGS="$GFX_WL_PKGS $FONTS"
    XORG_PKGS="$GFX_PKGS $FONTS xorg-minimal xorg-input-drivers setxkbmap xauth"
    SERVICES="sshd chronyd"

    case $variant in
        base)
            SERVICES="$SERVICES dhcpcd wpa_supplicant acpid"
        ;;     
	plasma)
	    PLASMA=yes
            PKGS="$PKGS $XORG_PKGS $WAYLAND_PKGS $D77_CORE $CALAMARES ark kde-plasma kde-baseapps sddm-kcm sddm discover flatpak xdg-desktop-portal-kde"
            SERVICES="$SERVICES dbus sddm NetworkManager polkitd power-profiles-daemon"
        ;;
        *)
            >&2 echo "Unknown variant $variant"
            exit 1
        ;;
    esac

    if [ "$COMMON" = yes ]; then
        include_common
    fi

    if [ "$PLASMA" = yes ]; then
        include_plasma
    fi

    if [ "$X11" = yes ]; then
        include_x11
    fi

    if [ "$WANT_INSTALLER" = yes ]; then
        include_installer
    else
        mkdir -p "$INCLUDEDIR"/usr/bin
        printf "#!/bin/sh\necho 'd77void-installer is not supported on this live image'\n" > "$INCLUDEDIR"/usr/bin/d77void-installer
        chmod 755 "$INCLUDEDIR"/usr/bin/d77void-installer
    fi

    if [ "$variant" != base ]; then
        setup_pipewire
    fi

    ./mklive.sh -a "$TARGET_ARCH" -o "$IMG" -p "$PKGS" -S "$SERVICES" -I "$INCLUDEDIR" \
		-T "duff-linux" \
        ${KERNEL_PKG:+-v $KERNEL_PKG} ${REPO} "$@"

	cleanup
}

if [ ! -x mklive.sh ]; then
    echo mklive.sh not found >&2
    exit 1
fi

if [ -n "$TRIPLET" ]; then
    IFS=: read -r ARCH DATE VARIANT _ < <( echo "$TRIPLET" | sed -Ee 's/^(.+)-([0-9rc]+)-(.+)$/\1:\2:\3/' )
    build_variant "$VARIANT" "$@"
else
    for image in $IMAGES; do
        build_variant "$image" "$@"
    done
fi