# common/calamares/modules/shellprocess.conf
---
dontChroot: false
timeout: 30
name: "shellprocess.conf"
script:
    - "mkdir -p /boot/efi"
    - "xbps-remove -Fy calamares"  # <--- This deletes the installer from the new system
    - "rm -f /etc/skel/.config/autostart/calamares.desktop"
    - "rm -rf /usr/share/calamares" # Optional: cleans up leftover config folders