#!/usr/bin/env bash

leftwm command "UnloadTheme"

pkill polybar &
pkill xcompmgr &
pkill dunst &
pkill redshift-gtk &
pkill nm-applet &
pkill volumeicon &
pkill octoxbps-notifier &
pkill udiskie &
pkill xautolock &
pkill cabtticon &

# Restore old dunst config
if [ -e $HOME/.config/dunstrc.bak ]; then
    rm $HOME/.config/dunst/dunstrc
    mv $HOME/.config/dunst/dunstrc.bak $HOME/.config/dunst/dunstrc
fi

pkill polybar
