#!/bin/bash

SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

#set background
if [ -x "$command -v wallc)" ]; then
    wallc set $SCRIPTPATH/down.jpg
fi

# if [ -x "/tmp/uhrwerk" ]; then
  # rm /tmp/uhrwerk
# fi

leftwm command "UnloadTheme"

pkill polybar &
pkill xcompmgr &
pkill dunst &
pkill redshift-gtk &
pkill nm-applet &
pkill volumeicon &
pkill octoxbps-notifier &
pkill udiskie &
pkill xautolock &
pkill cabtticon &
