#!/bin/bash

SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

#set background
if [ -x "$(command -v feh)" ]; then
  feh --bg-scale "$SCRIPTPATH"/down.jpg
fi

echo "UnloadTheme" > $XDG_RUNTIME_DIR/leftwm/commands.pipe

pkill polybar &
pkill xcompmgr &
pkill dunst &
pkill redshift &
pkill udiskie &
pkill xautolock &
pkill eww &
