#!/bin/bash
export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"
export EWW_DIR="$SCRIPTPATH/eww"

# Down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down

# Set the theme.toml config
# leftwm command "LoadTheme $SCRIPTPATH/theme.toml"
leftwm command "LoadTheme $SCRIPTPATH/theme.ron"
leftwm command "LoadTheme $SCRIPTPATH/theme.toml"

# Set background
if [ -x "$(command -v feh)" ]; then
    WALLPAPER=$(ls $SCRIPTPATH/background* | shuf -n 1)
    feh --bg-scale $WALLPAPER
fi

xcompmgr -c -f -n &
exec dunst &
redshift -l 41.6:-8.62 &
xautolock -time 15 - locker slock &
udiskie -a &
synclient TapButton1=1 &
synclient TapButton2=3 &
synclient TapButton3=2 &

pkill -9 -x eww 2>/dev/null || true
sleep 0.2
cd "$EWW_DIR" &
eww --config "$EWW_DIR" daemon &
eww --config "$EWW_DIR" open bar &
