#!/bin/bash
export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

# Down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down

# Set the theme.toml config
# leftwm command "LoadTheme $SCRIPTPATH/theme.toml"
leftwm command "LoadTheme $SCRIPTPATH/theme.ron"
leftwm command "LoadTheme $SCRIPTPATH/theme.toml"

# Set background
if [ -x "$(command -v feh)" ]; then
    WALLPAPER=$(ls $SCRIPTPATH/background* | shuf -n 1)
    feh --bg-scale $WALLPAPER
fi

# start eww daemon
eww daemon &

#open eww windows
eww open-many left tags right

polybar &
xcompmgr -c -f -n &
exec dunst &
redshift-gtk -l 41.6:-8.62 &
xautolock -time 5 - locker slock &
nm-applet &
volumeicon &
octoxbps-notifier &
udiskie -at &
synclient TapButton1=1 &
synclient TapButton2=3 &
synclient TapButton3=2 &

