#!/usr/bin/env bash

SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

leftwm-command "UnloadTheme"

pkill polybar &
pkill xcompmgr &
pkill dunst &
pkill redshift-gtk &
pkill nm-applet &
pkill volumeicon &
pkill octoxbps-notifier &
pkill udiskie &
pkill xautolock &
pkill cabtticon &
