#!/usr/bin/env bash
export $(dbus-launch)
SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P)"

#down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down

#set the theme.toml config
leftwm command "LoadTheme $SCRIPTPATH/theme.ron"
leftwm command "LoadTheme $SCRIPTPATH/theme.toml"


#set background
if [ -x "$(command -v feh)" ]; then
  WALLPAPER=$(ls "$SCRIPTPATH"/wallpaper* | shuf -n 1)
  feh --bg-scale $WALLPAPER
fi

dunst &
nm-applet &
xcompmgr -c -f -n &
/usr/bin/octoxbps-notifier &
volumeicon &
cbatticon &
redshift-gtk &

#boot polybar based on the number of monitors found
if [ -x "$(command -v polybar)" ]; then
  pkill polybar
  monitors="$(polybar -m | sed s/:.*// | tac)"
  while read -r display; do
    MONITOR=$display polybar -c "$SCRIPTPATH/polybar.config" mainbar &> /dev/null &
  done <<< "$monitors"
  exit 0
fi

