#!/bin/bash

# xmonad-void v1.0


# colors
    # echo
    normal="$(tput sgr0)"
    # Regular
    Ua="$(tput smul)"
    Ue="$(tput rmul)"
    Bold="$(tput bold)"
    Std="$(tput setaf 9)"
    black="$(tput setaf 0)"
    red="$(tput setaf 1)"
    green="$(tput setaf 2)"
    yellow="$(tput setaf 3)"
    blue="$(tput setaf 4)"
    magenta="$(tput setaf 5)"
    cyan="$(tput setaf 6)"
    white="$(tput setaf 7)"

# Functions

dots ()
{
    # dots until process ends
    while ps -p $spid > /dev/null 2>&1; do
        echo -n "."
        sleep .5
    done
}

enable_svs ()
{
    for i in $svs; do
        echo -n "- enable service \"$i\"... "
        ln -s /etc/sv/"$i" /var/service > /dev/null 2>&1
        if [ ! $? -eq 0 ]; then
            echo "${red}not enabled${normal}"
            error_svs=$error_svs"$i "
        else
            echo "${green}enabled${normal}"
        fi
    done
}

install_pkg ()
{
    for i in $pkg; do
        echo -n "- install \"$i\"..."
        xbps-install -y "$i" > /dev/null 2>&1 &
        spid=$!
        sleep .5
        dots &
        wait $spid
        if [ ! $? -eq 0 ]; then
            echo "${red}not installed${normal}"
        else
            echo "${green}installed${normal}"
        fi
    done
}

update ()
{
    xbps-install "$opt" > /dev/null 2>&1 &
        spid=$!
        sleep .5
        dots &
        wait $spid
        if [ ! $? -eq 0 ]; then
            echo "${red}no success${normal}"
        else
            echo "${green}success${normal}"
        fi
}

# Questions
read -p "Choose your language (us, de, fr, ...): " lang
while true; do
    userlist="$(cut -d ":" -f1 /etc/passwd)"
    found=0
    read -p "Enter your username (lower_case): " username
    for j in $userlist; do
        if [[ "$username" = "$j" ]]; then
            found=1
            break
        else
            continue
        fi
    done
    if [ "$found" -eq 1 ]; then
        echo -e "user found: \"$username\""
        break
    else
        echo -"no user \"$username\""
        while true; do
            read -p "try again (Y/n)? " yn
            case $yn in
                [Nn])
                    exit 0
                ;;
                [Yy]|"")
                    break
                ;;
                *)
                    echo "please answer y or n (Y or N)"
                ;;
            esac
        done
    fi
done

# Sync & Update
    echo
    echo "XBPS"
    xbps-install -uy xbps > /dev/null 2>&1
    echo -n "- update system..."; opt="-Suy"
        update "$opt"

# Tools install
    echo
    echo "Tools"
    pkg="curl git wget nano vim htop fastfetch libzip libzstd octoxbps xdg-user-dirs xdg-utils xdotool xtools"
    install_pkg "$pkg"
    xcheckrestart

# XMonad Dependencies
    echo
    echo "Xmonad Dependencies"
        pkg="cabal-install ghc git libX11-devel libXft-devel libXinerama-devel libXScrnSaver-devel ncurses-devel pkg-config xorg-minimal xterm"
        install_pkg "$pkg"
        echo "done"

# XMonad Install
    echo
    echo "Installing XMonad"
	cabal update
	cabal install --lib xmonad xmonad-contrib X11
    # Cabal's BIN dir to PATH
    echo "Adding Cabal's BIN dir to PATH"
	echo "export PATH="$HOME/.cabal/bin:$PATH"" >> ~/.bashrc
	source ~/.bashrc
    # XMonad Session
    echo "Creating XMonad Session"
	sudo mkdir -p /usr/share/xsessions
	sudo tee /usr/share/xsessions/xmonad.desktop > /dev/null << EOF
[Desktop Entry]
Name=XMonad
Comment=Lightweight tiling window manager
Exec=dbus-launch /home/$username/.cabal/bin/xmonad
Type=Application
EOF

# XMonad Configs
    echo
    echo "XMonad and Xmobar configs"
	cp -r xmo*/ ~/.config/
	cp -r Wallpaper/ ~/
	cp -r ../common/config/rofi ~/.config/

# XMonad Extra
    echo
    echo "Xmonad Dependencies"
        pkg="dbus dmenu gmrun NetworkManager rofi st slock sddm trayer-srg xmobar"
        svs="sddm dbus NetworkManager"
        install_pkg "$pkg"
        enable_svs "$svs"
        echo "done"

# Reboot
while true; do
    read -p "Reboot now (recommended)? [Y/n] " yn
    case $yn in
        [Yy]|"")
            reboot
            break
        ;;
        [Nn])
            exit 0
            break
        ;;
        *)
            echo "Please enter y or n (Y or N)?"
        ;;
    esac
done
