#!/bin/env bash

SELECTION=$(echo -e "󰒲 Suspend\n Logout\n Reboot\n Shutdown" | fuzzel -d -p " " -w 15 -l 4)

reboot_confirm() {
	SELECTION=$(echo -e "confirm reboot\ncancel reboot" | fuzzel -d -p " " -w 15 -l 2)
	case $SELCTION in
		"confirm reboot")
			reboot
			;;
		*)
			;;
	esac
}
shutdown_confirm() {
		SELECTION=$(echo -e "confirm shutdown\ncancel shutdown" | fuzzel -d -p " " -w 15 -l 2)
		case $SELCTION in
			"confirm shutdown")
				shutdown
				;;
			*)
				;;
		esac
}

case $SELECTION in
	"󰒲 Suspend")
		loginctl suspend
		;;
	" Logout")
		kill -9 -1
		;;
	" Reboot")
		loginctl reboot
		;;
	" Shutdown")
		loginctl poweroff
		;;
	*)
		;;
esac
