#!/bin/sh
#
# fluxbox startup-script:
#
# Lines starting with a '#' are ignored.

# Change your keymap:
xmodmap "~/.Xmodmap"

# Applications you want to run with fluxbox.
# MAKE SURE THAT APPS THAT KEEP RUNNING HAVE AN ''&'' AT THE END.
#
# unclutter -idle 2 &
# wmnd &
# wmsmixer -w &
# idesk &

# And last but not least we start fluxbox.
# Because it is the last app you have to run it with ''exec'' before it.
dunst &
cbatticon &
volumeicon &
nm-applet &
#redshift-gtk -l 41.6:-8.62 &
udiskie -at &
conky -c .conkyrc &
conky -c .conkyrc1 &
fbsetbg -f Wallpaper/background6.png &
xrdb merge ~/.Xresources &
/usr/bin/octoxbps-notifier &
xautolock -time 5 -locker slock &
synclient TapButton1=1 &
synclient TapButton2=3 &
synclient TapButton3=2 &
exec xcompmgr -c -f -n &
exec fluxbox
# or if you want to keep a log:
# exec fluxbox -log "~/.fluxbox/log"
